#!/usr/bin/env sh
# ONLY INSTALLS HOME FILES. NO SCRIPT IS PROVIDED FOR ROOT
set -e
PREFIX=$(realpath $(dirname "$0"))
for file in .clang-format .config/fish/config.fish .config/ghostty .config/kak \
            .profile .rustfmt.toml .vim/vimrc
do
    echo "Linking $file..."
    test \( ! -e "$HOME/$file" \) -o \( -L "$HOME/$file" \)
    ln -sf "$PREFIX/$file" "$HOME/$file"
done
echo 'Done!'
