" Enable filetype detection

filetype on
filetype plugin on

" 4 space tab

set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

" 2 space tab

autocmd FileType html setlocal ts=2 sts=2 sw=2
autocmd FileType javascript setlocal ts=2 sts=2 sw=2
autocmd FileType javascriptreact setlocal ts=2 sts=2 sw=2
autocmd FileType typescript setlocal ts=2 sts=2 sw=2
autocmd FileType typescriptreact setlocal ts=2 sts=2 sw=2
autocmd FileType css setlocal ts=2 sts=2 sw=2
autocmd FileType json setlocal ts=2 sts=2 sw=2
autocmd FileType xml setlocal ts=2 sts=2 sw=2
autocmd FileType yaml setlocal ts=2 sts=2 sw=2
autocmd FileType cmake setlocal ts=2 sts=2 sw=2
autocmd FileType haskell setlocal ts=2 sts=2 sw=2
autocmd FileType ocaml setlocal ts=2 sts=2 sw=2
autocmd FileType scheme setlocal ts=2 sts=2 sw=2
autocmd FileType dart setlocal ts=2 sts=2 sw=2
autocmd FileType j setlocal ts=2 sts=2 sw=2
autocmd FileType markdown setlocal ts=2 sts=2 sw=2
autocmd FileType uiua setlocal ts=2 sts=2 sw=2

" Automatic wrapping for mostly-text filetypes

autocmd FileType typst setlocal tw=80
autocmd FileType markdown setlocal tw=80

" Tab indent

autocmd FileType make setlocal noexpandtab

" Turn off tabs for Godot

let g:gdscript_recommended_style = 0

" Auto indent

filetype indent on
set autoindent
set smartindent

" Wrapped line movement

noremap j gj
noremap k gk

" Syntax highlighting

syntax on
set background=dark
colorscheme retrobox

" Show tab characters

set list
set listchars=tab:▸\ ,trail:·

" Speed up

set timeout
set timeoutlen=1000
set ttimeoutlen=0

" Show command

set showcmd

" Default filetypes

let g:asmsyntax='fasm'
let g:tex_flavor='latex'

" Scheme settings

autocmd FileType scheme setlocal lw+=define-library

" Search

set incsearch

" 80 character line

set colorcolumn=81

" 100 character line

autocmd FileType java setlocal cc=101
autocmd FileType kotlin setlocal cc=101
autocmd FileType rust setlocal cc=101

" Remove 80 character line in netrw

autocmd FileType netrw setlocal cc=

" Add relative numbers

set number
set relativenumber

" Configure mouse cursor

set mouse=a

" Syntax completion

set omnifunc=syntaxcomplete#Complete

" Load local vimrc

if filereadable('.vim/vimrc') && getcwd() != $HOME
    source .vim/vimrc
endif
