QT_QPA_PLATFORMTHEME=qt5ct
ANDROID_SDK_ROOT=$HOME/Coding/android/sdk
ANDROID_HOME=$ANDROID_SDK_ROOT
JAVA_HOME=/usr/lib/jvm/default
PATH=$PATH:$HOME/.cargo/bin
PATH=$PATH:$HOME/.local/bin
MOZ_ENABLE_WAYLAND=1 firefox
LIBVA_DRIVER_NAME=vdpau
